config/routes.rb
Rails.application.routes.draw do
  devise_for :users

 root "homes#top"
 resources :users
 resources :books
 get 'home/about' => 'homes#about'
 patch '/books', to: 'books#create'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
belongs_to :user

validates :title, presence: true
validates :body, presence: true, length: { maximum: 200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


         has_many  :books, dependent: :destroy
         attachment :profile_image

         validates :introduction, length: { maximum: 50 }
         validates :name, presence: true, length: { minimum: 2, maximum: 20}

         validates :name, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
	  user_path(resource)
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!

  before_action :ensure_current_user, {only: [:edit,:update,:destroy]}

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice] = "You have creatad book successfully."
    else
      @user = current_user
      @books = Book.all
     render :index
    end
  end

  def index
    @user = current_user
    @book = Book.new
    @booknew = Book.new
    @books = Book.all
  end

  def show
    @booknew = Book.new
    @book = Book.find(params[:id])
    @user = @book.user

  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       redirect_to book_path(@book.id)
       flash[:notice]="Book was successfully updated."
    else
    render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

private
    def book_params
      params.require(:book).permit(:title, :body)
    end

    def  ensure_current_user
      @book = Book.find(params[:id])
    if @book.user_id != current_user.id
       redirect_to books_path
    end
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

def top
end

def about
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!


  def show
     @user = User.find(params[:id])
     @booknew = Book.new
     @books = Book.where(user_id: @user.id)
  end

  def edit
     @user = User.find(params[:id])
    if @user == current_user
        render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def index
    @user = current_user
    @users = User.all
    @booknew = Book.new
    @books = Book.all
  end

  def update
    @user = User.find(params[:id])
   if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(current_user)
   else
      render :edit
   end
  end

   private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

 <div class="container">
  <div class="row">
   <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h1>Editing Book</h1>
      <%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
      <h4>Title</h4>
      <%= f.text_field :title %>
      <h4>Opinion</h4>
      <%= f.text_area :body %>
      <p><%= f.submit 'Update Book' %></p>
      <% end %>
    <%= link_to "Show", book_path(@book) %>
    |
    <%= link_to "Back", books_path %>
   </div>
  </div>
 </div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container">
  <div class="row">
    <%= render 'users/user', user: @user,book: @booknew %>

 <div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
   <thead>
    <th>Title</th>
    <th>Opinion</th>
   </thead>

    <% @books.each do |book| %>
     <tr>
       <td>
        <%= link_to user_path(book.user) do %>
        <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50,fallback: "no_image.jpg"%>
        <% end %>
        <%= link_to book.title, book_path(book.id) %>
       </td>
        <td><%= book.body %></td>
     </tr>
    <% end %>
   </table>
  </div>
 </div>
</div>

app/views/books/show.html.erb
<%= flash[:notice] %>

 <div class="container">
  <div class="row">
   <%= render 'users/user', user: @user,book: @booknew %>
    <div class="col-md-8 offset-md-1">
    <h2>Book</h2>
    <table class="table table-user-show">
     <tr>
      <td>
       <%= link_to user_path(@user) do %>
       <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg"%>
       <%= @user.name %>
       <% end %>
      </td>
      <td><%= link_to @book.title %></td>
      <td><%= @book.body %></td>
       <% if @book.user_id == current_user.id %>
        <td><%= link_to "Edit", edit_book_path(@book.id) %></td>
        <td><%= link_to "Destroy", book_path(@book.id), method: :delete, data: {confirm: "本当に消しますか？"} %></td>
       <% end %>
     </tr>
    </table>
   </div>
 </div>
</div>

app/views/homes/about.html.erb
   <div class = "about">
  <h1 class="px-3 mx-auto">Books</h1>
    </h1>
   </div>

app/views/homes/top.html.erb
<%= flash[:notice] %>
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i> Post Books !!</h1>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Books</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
    integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class="navbar-dark bg-dark">
      <div class="container">
        <div class="row">
         <div class="col-md-7">
          <nav>
             <a class="navbar-brand" href="/"><span>Books</span></a>
          </nav>
         </div>
          <div class="col-md-5">
           <ul class= "bar">
             <nav class="navbar-brand">
              <% if user_signed_in? %>
                <li><a class="fas fa-home nav-link text-light" <%= link_to "Home", user_path(current_user.id) %> </a></li>
                <li><a class="fas fa-users nav-link text-light" href="/users"> Users</a></li>
                <li><a class="fas fa-book-open nav-link text-light" href="/books"> Books</a></li>
                <li><a class="fas fa-sign-out-alt nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out"> Log out</a></li>
              <% else %>
                <li><a class="fas fa-home nav-link text-light" href="/"> Home</a></li>
                <li><a class="fas fa-link nav-link text-light" href="/home/about"> About</a></li>
                <li><a class="fas fa-user-plus nav-link text-light" href="/users/sign_up"> Sign up</a></li>
                <li><a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in"> Log in</a></li>
              <% end %>
            </nav>
           </ul>
         </div>
        </div>
       </div>
    </header>
              <%= yield %>
    <footer>
        <div class="d-flex align-items-center justify-content-center">
          <p>practice ruby</p>
        </div>
    </footer>

  </body>
</html>

app/views/users/_user.html.erb
<div class="col-md-3">
  <table class="table table-user">>
 　　<h2>User info</h2>
  　<%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image2.jpg"%>
 　<tr>
    <th>name</th>
    <th><%= user.name %></th>
   </tr>
   <tr>
    <th>Introduction</th>
    <th><%= user.introduction %></th>
   </tr>
  </table>
 <p><%= link_to "編集", edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %></p>

  <%= form_with model: book, url:'/books', local:true do |f| %>
  <h2>New book</h2>
  <h5>Title</h5>
  <%= f.text_field :title %>
  <h5>Opinipn</h5>
  <%= f.text_field :body %>
  <p><%= f.submit 'Create Book',class: "col-xs-12 btn btn-primary" %></p>
  <% end %>
</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= form_with model:@user, local:true do |f| %>
<h4>Name</h4>
<%= f.text_field :name %>
<h4>Image</h4>
<%= f.attachment_field :profile_image %>
<h4>Introduction</h4>
<%= f.text_area :introduction %>
<%= f.submit 'Update User' %>
<% end %>

app/views/users/index.html.erb
<div class="container">
 <div class="row">
   <%= render 'users/user', user: @user,book: @booknew %>
    <div class="col-md-8 offset-md-1">
     <h2>Users</h2>
     <table class="table">
      <thead>
       <th>image</th>
       <th>name</th>
      </thead>

         <% @users.each do |user| %>
          <tr>
          	<td><%= attachment_image_tag user, :profile_image, :fill, 50, 50,fallback: "no_image.jpg"%></td>
          	<td><%= user.name %></td>
          	<td><%= link_to "Show", "/users/#{user.id}" %></td>
          </tr>
      <% end %>
     </table>
    </div>
　</div>
 </div>

app/views/users/show.html.erb
<%= flash[:notice] %>

<div class="container">
 <div class="row">
  <%= render 'users/user',  user: @user,book: @booknew %>
   <div class="col-md-8 offset-md-1">
   <h2>Books</h2>
    <table class="table table-hover table-inverse">
     <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    　</thead>
   　<tbody>
     <% @books.each do |book| %>
     <%= link_to user_path(@user.id) do %>
      <tr>
        <td><%= attachment_image_tag book.user, :profile_image, :fill, 50, 50,fallback: "no_image.jpg"%></td>
      　<td><%= link_to book.title, book_path(book.id) %></td>
      　<% end %>
       <td><%= book.body %></td>
      </tr>
     <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>